[language_servers.ty]
enabled = true

[language_servers.basedpyright]
enabled = false

[language_servers.pylsp]
enable_ruff = true
enable_pyflakes = false
enable_pylint = false
enable_flake8 = false
enable_pydocstyle = false
enabled = true
enable_mypy = true

[experimental]
inline_ai_tooltip = true
performant_table_charts = true
rtc_v2 = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[completion]
copilot = false
activate_on_typing = true

[diagnostics]
enabled = true

[display]
dataframes = "rich"
reference_highlighting = false
default_width = "medium"
cell_output = "above"
theme = "dark"
default_table_max_columns = 50
default_table_page_size = 10
code_editor_font_size = 14

[server]
browser = "default"
follow_symlink = false

[package_management]
manager = "uv"

[formatting]
line_length = 79

[runtime]
output_max_bytes = 8000000
default_auto_download = []
auto_instantiate = true
default_sql_output = "auto"
on_cell_change = "autorun"
auto_reload = "off"
watcher_on_save = "lazy"
reactive_tests = true
std_stream_max_bytes = 1000000

[ai]
rules = ""
mode = "manual"

[ai.google]

[ai.anthropic]

[ai.bedrock]

[ai.open_ai]

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[snippets]
custom_paths = []
include_default_snippets = true
